### ISSUE TITLE
image_emotion_gender_demo.py 컴파일이 되지 않습니다.

### ISSUE THREAD

**Issue by Kingwon2** [Kingwon2/7708_subject#1]
image_emotion_gender_demo.py 컴파일이 되지 않습니다.
(window 10)
requirement의 요구사항되고 환경을 구성했는데 에러가 계속뜹니다. 어떻게 해야하나요?
` Traceback (most recent call last):
File "C:\Users\박태원\Downloads\EMOTION_RECOGNITION_ALL_DATA\face_classification-master\src\image_emotion_gender_demo.py", line 42, in 
rgb_image = load_image(image_path, grayscale=False)
File "C:\Users\박태원\Downloads\EMOTION_RECOGNITION_ALL_DATA\face_classification-master\src\utils\inference.py", line 7, in load_image
pil_image = image.load_img(image_path, grayscale, target_size)
File "C:\Users\박태원\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\keras_preprocessing\image.py", line 509, in load_img
raise ValueError('color_mode must be "grayscale", "rbg", or "rgba"')
ValueError: color_mode must be "grayscale", "rbg", or "rgba" `

**Comment by Theeea** [comment]
내가 REQUIREMENTS.txt 수정한거 커밋한거 있는데 그거 너 브랜치로 merge해서
pip install -r requirements.txt 이거 실행하고 하면 됨.
